### ISSUE TITLE
flow focus-check

### ISSUE THREAD

**Issue by sibelius** [HenriBeck/check-flow#68]
`flow focus-check` check only files that was passed to flow

the problem is that it will show errors of others files as well

`flow focus-check a.js` could show errors of `b.js` as `a.js` depends on `b.js`

it would be very helpfull for lint-staged configs to ignore `b.js` for now

**Comment by HenriBeck** [comment]
Yeah makes sense. Can lint staged pass the files to a flag?

If yes I would introduce an _only_ flag to only report on those files.
If not we could just allow for files to be passed in as the main argument.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sibelius** [comment]
lint-staged will pass a list of files to flow focus-check

**Comment by HenriBeck** [comment]
@sibelius should be supported in v1.0.0. Might need some testing

**Comment by sibelius** [comment]
tks, I'll try
